src/Celmedia/Toyocosta/VehiculosBundle/Entity/SlidePrincipal.php
<?php

namespace Celmedia\Toyocosta\VehiculosBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
/**
 * SlidePrincipal
 */
class SlidePrincipal
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $link;

    /**
     * @var string
     */
    private $descripcion;

    /**
     * @var string
     */
    private $imagen_banner;

    /**
     * @var string
     */
    private $imagen_movil;

    /**
     * @var string
     */
    private $seccion;

    /**
     * @var string
     */
    private $boton;

    /**
     * @var integer
     */
    private $estado;

    /**
     * @var \DateTime
     */
    private $created;

    /**
     * @var \DateTime
     */
    private $updated;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set link
     *
     * @param string $link
     * @return SlidePrincipal
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Get link
     *
     * @return string 
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Set descripcion
     *
     * @param string $descripcion
     * @return SlidePrincipal
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string 
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set imagen_banner
     *
     * @param string $imagenBanner
     * @return SlidePrincipal
     */
    public function setImagenBanner($imagenBanner)
    {
        $this->imagen_banner = $imagenBanner;

        return $this;
    }

    /**
     * Get imagen_banner
     *
     * @return string 
     */
    public function getImagenBanner()
    {
        return $this->imagen_banner;
    }

    /**
     * Set imagen_movil
     *
     * @param string $imagenMovil
     * @return SlidePrincipal
     */
    public function setImagenMovil($imagenMovil)
    {
        $this->imagen_movil = $imagenMovil;

        return $this;
    }

    /**
     * Get imagen_movil
     *
     * @return string 
     */
    public function getImagenMovil()
    {
        return $this->imagen_movil;
    }

    /**
     * Set seccion
     *
     * @param string $seccion
     * @return SlidePrincipal
     */
    public function setSeccion($seccion)
    {
        $this->seccion = $seccion;

        return $this;
    }

    /**
     * Get seccion
     *
     * @return string 
     */
    public function getSeccion()
    {
        return $this->seccion;
    }

    /**
     * Set boton
     *
     * @param string $boton
     * @return SlidePrincipal
     */
    public function setBoton($boton)
    {
        $this->boton = $boton;

        return $this;
    }

    /**
     * Get boton
     *
     * @return string 
     */
    public function getBoton()
    {
        return $this->boton;
    }

    /**
     * Set estado
     *
     * @param integer $estado
     * @return SlidePrincipal
     */
    public function setEstado($estado)
    {
        $this->estado = $estado;

        return $this;
    }

    /**
     * Get estado
     *
     * @return integer 
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return SlidePrincipal
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return SlidePrincipal
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime 
     */
    public function getUpdated()
    {
        return $this->updated;
    }
    /**
     * @ORM\PrePersist
     */
    public function lifecycleFileUpload()
    {
        // Add your code here
        $this->uploadImagenSlide();
        $this->uploadImagenMobilBanner();
    }


            /**
     * Unmapped property to handle file uploads
     */
    private $ImagenSlide;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setImagenSlide(UploadedFile $ImagenSlide = null)
    {
        $this->ImagenSlide = $ImagenSlide;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getImagenSlide()
    {
        return $this->ImagenSlide;
    }

    /**
     * Manages the copying of the file to the relevant place on the server
     */
    public function uploadImagenSlide()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getImagenSlide()) {
            return;
        }

        // move takes the target directory and target filename as params
        $this->getImagenSlide()->move(
           __DIR__.'/../../../../../web/'. 'uploads/slide-principal' ,
            $this->getImagenSlide()->getClientOriginalName()
        );

        // set the path property to the filename where you've saved the file
        $this->imagen_banner = $this->getImagenSlide()->getClientOriginalName();

        // clean up the file property as you won't need it anymore
        $this->setImagenSlide(null);
    }



            /**
     * Unmapped property to handle file uploads
     */
    private $ImagenMobilBanner;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setImagenMobilBanner(UploadedFile $ImagenMobilBanner = null)
    {
        $this->ImagenMobilBanner = $ImagenMobilBanner;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getImagenMobilBanner()
    {
        return $this->ImagenMobilBanner;
    }

    /**
     * Manages the copying of the file to the relevant place on the server
     */
    public function uploadImagenMobilBanner()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getImagenMobilBanner()) {
            return;
        }

        // move takes the target directory and target filename as params
        $this->getImagenMobilBanner()->move(
           __DIR__.'/../../../../../web/'. 'uploads/slide-principal/mobil' ,
            $this->getImagenMobilBanner()->getClientOriginalName()
        );

        // set the path property to the filename where you've saved the file
        $this->imagen_movil = $this->getImagenMobilBanner()->getClientOriginalName();

        // clean up the file property as you won't need it anymore
        $this->setImagenMobilBanner(null);
    }


    public function __toString()
    {
        return $this->getLink();
    }



}

src/Celmedia/Toyocosta/VehiculosBundle/Controller/CustomController.php
<?php

namespace Celmedia\Toyocosta\VehiculosBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\Input;

class CustomController extends Controller
{


    /**********CUSTOM************/
    public function homeAction(){
        
        $em = $this->getDoctrine()->getManager();
        
        $categoriasVehiculo = $this->getDoctrine()->getRepository('CelmediaToyocostaVehiculosBundle:CategoriaVehiculo')->findBy( array("estado"=> 1) );



        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:index.html.twig', array('categoriasVehiculo' => $categoriasVehiculo ) );

    }

    public function verVehiculoAction($id){
        $em = $this->getDoctrine()->getManager();

        $vehiculo = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:Vehiculo")->findOneBy(array(
            "id" => $id,
            "estado" => 1
                )
        );

        $vehiculoSlide = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:SlideVehiculos")->findOneBy(array(
            "vehiculo_slide" => $id , "estado" => 1
                )
        );


        $vehiculoColores = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:VehiculoColores")->findBy(array(
            "vehiculo" => $vehiculo,
            "estado" => 1
                )
        );
        $vehiculoModelos = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:VehiculoModelos")->findBy(array(
            "vehiculomodel" => $vehiculo,
            "estado" => 1
                )
        );

        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:vehiculo.html.twig' , array(
            "vehiculo" => $vehiculo,
            "vehiculoColores" => $vehiculoColores,
            "vehiculoModelos" => $vehiculoModelos,
            "vehiculoSlide" => $vehiculoSlide,
            //"vehiculoGaleria" => $vehiculoGaleria
        ));
    }

    public function homeVehiculosAction(){
        $em = $this->getDoctrine()->getManager();
        
        $slidePrincipal = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:SlidePrincipal")->findBy(array(
            "estado" => 1 , "seccion" => "principal"
                )
        );



        $categoriaid =$this->getDoctrine()->getRepository('CelmediaToyocostaVehiculosBundle:CategoriaVehiculo')->findOneBy(array("nombre" => "autos", "estado"=> 1));
        $vehiculosautos = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:SlideVehiculos")->findBy(array(
            "categoria_vehiculo" => $categoriaid , "estado" => 1
                )
        );

        
        $camionetaid =$this->getDoctrine()->getRepository('CelmediaToyocostaVehiculosBundle:CategoriaVehiculo')->findOneBy(array("nombre" => "camionetas", "estado"=> 1));
        $vehiculoscamionetas = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:SlideVehiculos")->findBy(array(
            "categoria_vehiculo" => $camionetaid , "estado" => 1
                )
        );

        $terrenoid =$this->getDoctrine()->getRepository('CelmediaToyocostaVehiculosBundle:CategoriaVehiculo')->findOneBy(array("nombre" => "suv", "estado"=> 1));
        $vehiculostodoterreno = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:SlideVehiculos")->findBy(array(
            "categoria_vehiculo" => $terrenoid , "estado" => 1
                )
        );


        function shuffle_assoc($array)
        {
            // Initialize
                $shuffled_array = array();

            // Get array's keys and shuffle them.
                $shuffled_keys = array_keys($array);
                shuffle($shuffled_keys);

            // Create same array, but in shuffled order.
                foreach ( $shuffled_keys AS $shuffled_key ) 
                {
                    $shuffled_array[  $shuffled_key  ] = $array[  $shuffled_key  ];
                } 
            // Return
                return $shuffled_array;
        }


        $autos = shuffle_assoc($vehiculosautos); //randomize
        $camionetas = shuffle_assoc($vehiculoscamionetas); //randomize
        $todoterreno = shuffle_assoc($vehiculostodoterreno); //randomize



        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:home.vehiculos.html.twig' , array( "slidePrincipal" => $slidePrincipal, 'autos' => $autos, 'camionetas' => $camionetas, 'todoterreno' => $todoterreno ));
    }

    public function exoneradosHomeAction(){


        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:exonerados.html.twig' , array());
    }

    public function postventaAction(){


        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:postventa.html.twig' , array());
    }

    public function exoneradosInfoAction($tipo)
    {
        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:exonerados_info.html.twig' , array("tipo" => $tipo));

    }
    public function talleresyserviciosAction()
    {
        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:talleresyservicios.html.twig' , array());        
    }

    public function certificadostoyocostaAction()
    {
        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:certificados.html.twig' , array());        
    }


    public function testdriveCustomAction(Request $request)
    {
        
        $em = $this->getDoctrine()->getManager();        
        
        $agencias = $this->getDoctrine()->getRepository("CelmediaToyocostaContenidoBundle:Establecimiento")->findBy(array(
            "estado" => 1
                )
        );

        $vehiculos_test = $this->getDoctrine()->getRepository("CelmediaToyocostaContenidoBundle:VehiculoTest")->findBy(array(
            "estado" => 1
                )
        );

        if ($request->isMethod('POST')) {

            $nombre = $request->request->get('nombre');
            $apellido = $request->request->get('apellido');
            $telefono = $request->request->get('telefono');
            $email = $request->request->get('email');
            $cedula = $request->request->get('cedula');
            $nacimiento = $request->request->get('nacimiento');
            $agencia = $request->request->get('agencia');
            $ciudad = $request->request->get('ciudad');
            $vehiculo = $request->request->get('vehiculo');
            $fecha_test = $request->request->get('fecha_test');
            $hora_test = $request->request->get('hora_test');
            $observacion = $request->request->get('observacion');

    

            $info = new \Celmedia\Toyocosta\ContenidoBundle\Entity\InfoTestDrive();

            $info->setNombre( $nombre  );
            $info->setApellido( $apellido  );
            $info->setTelefono( $telefono  );
            $info->setEmail( $email  );
            $info->setCedula( $cedula);
            $info->setFechaNacimiento( new \DateTime($nacimiento) );
            $info->setAgencia( $agencia  );
            $info->setCiudad( $ciudad  );
            $info->setVehiculo($vehiculo);
            $info->setFechaTest( new \DateTime($fecha_test ) );
            $info->setHoraTest( $hora_test  );
            $info->setObservaciones( $observacion  );
            
            
            $em = $this->getDoctrine()->getManager(); 
            $em->persist(  $info );
            $em->flush();

            $formulario = "testdrive";

            if( $this->enviarCorreo($email, $info, $formulario ) ){
                return new JsonResponse(array(
                    'codigo' => 1,
                    'Mensaje' => "El mensaje ha sido enviado"
                ), 200); //codigo de error diferente
            }else{
                return new JsonResponse(array(
                    'codigo' => 0,
                    'Mensaje' => "No se ha recibido vehiculo"
                ), 200); //codigo de error diferente
            }




           



        }



        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:testdrive.html.twig' , array( "agencias" => $agencias , "vehiculos_test"=> $vehiculos_test  ));

    }

    public function citatalleresAction($tipo)
    {
        
        $tipo = $tipo;

        $em = $this->getDoctrine()->getManager();        
        
        $vehiculos = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:Vehiculo")->findBy(array(
            "estado" => 1
                )
        );

        $reservas = $this->getDoctrine()->getRepository("CelmediaToyocostaContenidoBundle:TipoReserva")->findBy(array(
            "estado" => 1
                )
        );
        

        $banners = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:SlidePrincipal")->findBy(array(
            "estado" => 1 , "seccion" => "mantenimiento"
                )
        );



        return $this->render('CelmediaToyocostaVehiculosBundle:Custom:citatalleres.html.twig' , array( "vehiculos" => $vehiculos , "reservas" => $reservas , "banners" => $banners, "tipo" => $tipo ));


    }

    public function tallermovilAction($value='')
    {
        
        $em = $this->getDoctrine()->getManager();        
        
        $vehiculos = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:Vehiculo")->findBy(array(
            "estado" => 1
                )
        );

        $reservas = $this->getDoctrine()->getRepository("CelmediaToyocostaContenidoBundle:TipoReserva")->findBy(array(
            "estado" => 1
                )
        );
        

        $banners = $this->getDoctrine()->getRepository("CelmediaToyocostaVehiculosBundle:SlidePrincipal")->findBy(array(
            "estado" => 1 , "seccion" => "mantenimiento"
                )
        );

src/Celmedia/Toyocosta/VehiculosBundle/Resources/views/Custom/certificados.html.twig
{% extends 'CelmediaToyocostaVehiculosBundle::template.html.twig' %}

{% block seo %}
    
    <title>TOYOCOSTA | Certificados Seminuevos</title>
    
    <meta name="description" content="Todas la unidades seminuevas Toyocosta pasas por una intensa revisión que incluye avalúo técnico, garantía mecánica y documentación en regla."/>

    <meta name="keywords" content="concesionario toyota guayaquil, toyocosta certificados, verificación toyocosta, garantia Toyota, toyocosta avaluo" />

{% endblock %}


{% block bannercabecera %}

        <header>

            {% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/certificados.jpg' %}
            <img src="{{ asset_url }}" id="logoblanco" alt="Toyocosta" class="img-responsive"  style="width:100%;" />
            {% endimage %}

        </header>
    
{% endblock %}


{% block contenidotoyocosta %}

    <div class="container">
        <div class="row">
            <div class="col-md-12" style="padding-left: 0px;">
                <ol class="breadcrumb">
                    <li>
                        <a href="{{ path('toyocosta_homepage') }}">Inicio</a>
                    </li>
                    <li class="active">Certificados</li>
                </ol>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center titular">UNIDADES VERIFICADAS POR TOYOCOSTA</h1>
            </div>
        </div>


        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <p class="text-center parrafo">TOYOCOSTA está impulsando la DIVISIÓN USADOS con mucha fuerza ofreciendo versatilidad en este negocio. Nos diferenciamos de la competencia (patios de usados y divisiones de usados de otros concesionarios) en que vendemos unidades que han pasado por una revisión completa de TOYOCOSTA en aspectos técnicos y legales. Este año, seguimos creciendo y ofrecemos.</p>
            </div>
        </div>

        <div class="row tb-20">
            <div class="col-md-4">
                <div class="ficha-certificado">
                   
                    {% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/icon/c-toyota.png' %}
                    <img src="{{ asset_url }}" id="logoblanco" alt="Toyocosta" class="img-responsive img-center" />
                    {% endimage %}

                    <h4 class="text-center">VERIFICACI&Oacute;N TOYOCOSTA</h4> 
                    <p class="text-center parrafo" style="padding: 0px 10px;">Es un informe que asegura que nuestro Seminuevo ha pasado por un avalúo técnico completo y no tiene gravamen/prohibición de enajenar.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ficha-certificado">
                   
                    {% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/icon/grabame.png' %}
                    <img src="{{ asset_url }}" id="logoblanco" alt="Toyocosta" class="img-responsive img-center" />
                    {% endimage %}

                    <h4 class="text-center">TRASPASO DE GARANT&Iacute;A TOYOTA</h4> 
                    <p class="text-center parrafo" style="padding: 0px 10px;">Si el vehículo es TOYOTA y ha realizado todos las visitas de mantenimiento con los talleres autorizados y está dentro de los 5 años/100mil km, mantiene su garantía, misma que se trapasa al nuevo dueño.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ficha-certificado">
                   
                    {% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/icon/garantia.png' %}
                    <img src="{{ asset_url }}" id="logoblanco" alt="Toyocosta" class="img-responsive img-center" />
                    {% endimage %}

                    <h4 class="text-center">GARANT&Iacute;A MEC&Aacute;NICA</h4> 
                    <p class="text-center parrafo" style="padding: 0px 10px;">Toyocosta garantiza la calidad de todas las unidades, las mismas que pasan por un proceso de alistamiento para ofrecer un producto final de primera.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="ficha-certificado">
                   
                    {% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/icon/avaluo.png' %}
                    <img src="{{ asset_url }}" id="logoblanco" alt="Toyocosta" class="img-responsive img-center" />
                    {% endimage %}

                    <h4 class="text-center">AVAL&Uacute;O T&Eacute;CNICO</h4> 
                    <p class="text-center parrafo" style="padding: 0px 10px;">Nuestros técnicos realizan una rigurosa inspección de 30 puntos para tomar las unidades, todos nuestros vehículos cumplen con un estándar de calidad.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ficha-certificado">
                   
                    {% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/icon/documentos-en-reglas.png' %}
                    <img src="{{ asset_url }}" id="logoblanco" alt="Toyocosta" class="img-responsive img-center" />
                    {% endimage %}

                    <h4 class="text-center">DOCUMENTOS EN REGLA</h4> 
                    <p class="text-center parrafo" style="padding: 0px 10px;">Nuestros Vehículos salen del concesionario con toda la documentación en regla, garantizándole a nuestros clientes que no tendrán ningún inconveniente legal en la trasferencia de las unidades.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ficha-certificado">
                   
                    {% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/icon/credito.png' %}
                    <img src="{{ asset_url }}" id="logoblanco" alt="Toyocosta" class="img-responsive img-center" />
                    {% endimage %}

                    <h4 class="text-center">CR&Eacute;DITO DIRECTO</h4> 
                    <p class="text-center parrafo" style="padding: 0px 10px;">Desde el 30% de entrada hasta 36 meses plazo, Pre calificación del crédito en 15 minutos, Trabajamos con crédito en instituciones financieras.</p>
                </div>
            </div>
        </div>

        <div class="row" style="padding-bottom:150px;"></div>

    </div>



{% endblock %}

src/Celmedia/Toyocosta/VehiculosBundle/Resources/views/Custom/home.vehiculos.html.twig
        <!-- Vehiculos -->
            <div class="container-fluid">
                    
                <div class="row text-center">

                    <div class="col-md-4">
                        <div class="row">
                            {% for camioneta in camionetas %}
                                {% if loop.first %}

                                    <figure class="imghome" >
                                        {#{% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/accesos/camionetas/hilux-2016-4X2.jpg' %}
                                        <img src="{{ asset_url }}" alt="" class="img-responsive"/>
                                        {% endimage %}#}
                                        <img src="{{ asset('uploads/slide-vehiculos/portada/'  ~   camioneta.imagenSlide ) }}" alt="" class="img-responsive" />
                                        <figcaption>    
                                            <div class="caption">
                                                <h2 class="title-accesos">Camionetas</h2>
                                                <a href="{{ path('custom_vehiculo', {"categoria": "Camionetas" ,"nombre": camioneta.vehiculoSlide.nombre ,'id': camioneta.vehiculoSlide.id } )  }}">
                                                    <div class="btn btn-home">Explorar {{camioneta.vehiculoSlide.nombre }}</div>
                                                </a>
                                                <p>
                                                    <a href="{{path('custom_vehiculos')}}" target="_blank" style="background-color: transparent; text-decoration:none;color: #fff;">Ver todas las camionetas</a>
                                                </p>
                                            </div>
                                            <a href="http://www.toyocosta.com/blog">Ver todas las camionetas</a>
                                        </figcaption> 
                                    </figure> 

                                {% endif %}
                            {% endfor %}
                        </div>
                        
                    </div>

                    <div class="col-md-4">

                        <div class="row">
                            {% for item in autos  %}
                                {% if loop.first %}
                                    <figure class="imghome" >

                                        <img src="{{ asset('uploads/slide-vehiculos/portada/'  ~   item.imagenSlide ) }}" alt="" class="img-responsive" />

                                        <figcaption>    
                                            <div class="caption">
                                                <h2 class="title-accesos">Autos</h2>
                                                <a href="{{ path('custom_vehiculo', {"categoria": "Autos" ,"nombre": item.vehiculoSlide.nombre ,'id': item.vehiculoSlide.id } )  }}">
                                                    <div class="btn btn-home">Explorar {{item.vehiculoSlide.nombre }}</div>
                                                </a>
                                                <p>
                                                    <a href="{{path('custom_vehiculos')}}" target="_blank" style="background-color: transparent; text-decoration:none;color: #fff;">Ver todos los autos</a>
                                                </p>
                                            </div>
                                            <a href="{{path('custom_vehiculos')}}">Ver todos los autos</a>
                                        </figcaption> 

                                    </figure>   

                                {% endif %}
                            {% endfor %}

                        </div>

                    </div>

                    <div class="col-md-4">
                        <div class="row">
                            {% for row in todoterreno %}
                                {% if loop.first %}

                                    <figure class="imghome" >
                                        {#{% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/accesos/todoterreno/fortuner.jpg' %}
                                        <img src="{{ asset_url }}" alt="" class="img-responsive"/>
                                        {% endimage %}#}
                                        <img src="{{ asset('uploads/slide-vehiculos/portada/'  ~   row.imagenSlide ) }}" alt="" class="img-responsive" />

                                        <figcaption>    
                                            <div class="caption">
                                                <h2 class="title-accesos">Suv</h2>
                                                <a href="{{ path('custom_vehiculo', {"categoria": "TodoTerreno" ,"nombre": row.vehiculoSlide.nombre ,'id': row.vehiculoSlide.id } )  }}">
                                                    <div class="btn btn-home">Explorar {{row.vehiculoSlide.nombre }}</div>
                                                </a>
                                                <p>
                                                    <a href="{{path('custom_vehiculos')}}" target="_blank" style="background-color: transparent; text-decoration:none;color: #fff;">Ver todos los Suv</a>
                                                </p>
                                            </div>
                                            <a href="http://www.toyocosta.com/blog">Ver todos los Suv</a>
                                        </figcaption> 
                                    </figure> 

                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {#<div class="col-md-4">
                        <div class="row">
                            <figure class="imghome" >
                                {% image '@CelmediaToyocostaVehiculosBundle/Resources/public/custom/img/accesos/exonerados.jpg' %}
                                <img src="{{ asset_url }}" alt="" class="img-responsive"/>
                                {% endimage %}
                                <figcaption>    
                                    <div class="caption" style="padding-bottom:20px;">
                                        <h2 class="title-accesos">Exonerados</h2>
                                        <a href="{{path('usados')}}">
                                            <div class="btn btn-home">Ver m&aacute;s</div>
                                        </a>
                                        <p style="visibility:hidden;">
                                            <a href="{{path('custom_vehiculos')}}" target="_blank" style="background-color: transparent; text-decoration:none;color: #fff;">Ver todo terreno</a>
                                        </p>                                        
                                    </div>
                                </figcaption> 
                            </figure> 
                        </div>
                        
                        
                    </div>#}
                </div>
                
            </div>